### ISSUE TITLE
Duplicate key problem in json

### ISSUE THREAD

**Issue by tokoba** [fairy-root/Flux-Prompt-Generator#3]
I found body_types.json does not work correctly and fixed the issue. Hopefully the following explanation helps.

# Problem
Not all the items shown on ComfyUI Prompt selection of body types.
When I press right arrow button repeatedly, then  the choices loop after "overweight" and jump to "fat" repeatedly.

# Cause of the problem
I checked the data file,  I noticed there are two "overweight" items, and two "flabby" items.
It seems to be when python loads the duplicate items, then it could have misjudged the current item number and returned to the next position of the FIRST item. In this case, the next item of the first "overweight" was "fat".

# Debug
I erased those duplicate items ("overweight", "flabby"), and restart ComfyUI, then problem solved.
The strange loop does not occur.

# Solutions
## delete duplicate keys manually
Simple and it worked. But if there are a lot of files, you could overlook.

## Python program fix
flux_prompt_generator.py
Following code is an example of duplicate item remover when loading json files.
```python
import json
import os

def remove_duplicates(list):
    seen = set()  # set is used for "non-duplicate" data structure
    result = []
    for item in list:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result

def load_json_file(file_name):
    file_path = os.path.join(os.path.dirname(__file__), "data", file_name)
    with open(file_path, "r") as file:
        temp_list = json.load(file)
        print(temp_list)   #for debug(duplicate items still exist)
        return remove_duplicates(temp_list)

BODY_TYPES = load_json_file("body_types.json")
print(BODY_TYPES)  # for debug (duplicate items removed)
```

## body_types.json duplicate items *, ** marked
```json
[
    "pretty",
    "chubby",
    "midweight",
    "overweight",           *
    "fat",
    "flabby",                     **
    "buxom",
    "voluptuous",
    "hefty",
    "pudgy",
    "plump",
    "obese",
    "morbidly obese",
    "stout",
    "rotund",
    "thick-bodied",
    "thicc",
    "thick",
    "beefy",
    "portly",
    "tubby",
    "overweight",            *
    "(slightly overweight)",
    "buff",
    "burly",
    "fit",
    "well-built",
    "well-endowed",
    "muscular",
    "stocky",
    "big-boned",
    "curvy",
    "flabby",                       **
    "flyweight",
    "skinny",
    "too skinny",
    "anorexic",
    "not skinny",
    "slender",
    "lanky",
    "slim",
    "slight"
]
```

**Comment by fairy-root** [comment]
thank you for noting that, It has already been fixed
