### ISSUE TITLE
FluxPromptGenerator.IS_CHANGED() issue 

### ISSUE THREAD

**Issue by paulrus** [fairy-root/Flux-Prompt-Generator#4]
When using this node, I keep getting this error in the command line / log:

WARNING: FluxPromptGenerator.IS_CHANGED() got an unexpected keyword argument 'seed'
clip missing: ['text_projection.weight']
Requested to load FluxClipModel_
Loading 1 new model
loaded completely 0.0 9319.23095703125 True

I'm very non-technical, but I assume the seed value is passing along something unexpected for some reason.

-Paul

**Comment by fairy-root** [comment]
The code has been updated, you're missing the duplicates that have been deleted. Delete the node and update it via git URL

**Comment by paulrus** [comment]
Thanks!

**Comment by jonny7737** [comment]
On a mac, I have the same warning. I followed your instructions above. I removed and reinstall via Manager. I manually installed via git clone. I just tried git pull.

I still have the warning. Is it a mac thing?

**Comment by paulrus** [comment]
Sorry, but I've pulled the latest version and still get the same thing.  

WARNING: FluxPromptGenerator.IS_CHANGED() got an unexpected keyword argument 'seed'
Requested to load FluxClipModel_

**Comment by jonny7737** [comment]
> Sorry, but I've pulled the latest version and still get the same thing.
> 
> WARNING: FluxPromptGenerator.IS_CHANGED() got an unexpected keyword argument 'seed' Requested to load FluxClipModel_

Are you using a mac or something else?

**Comment by paulrus** [comment]
Windows 11 pc.  I tried to sort out why it was passing seed along but I really don't know Python so nothing I did made a difference.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fairy-root** [comment]
I can't seem to reproduce the issue, I am on windows 11 as well, and the node is on version 1.0.1

**Comment by jonny7737** [comment]
I am on a mac and I get the same warning. Could be wrong but it doesn't seem to break anything.

**Comment by fairy-root** [comment]
Unfortunately I don't have a Mac so please, if anyone can debug the function is_changed() please let me know of what I should change.

**Comment by LiJT** [comment]
I m on Windows 10, I got the very same warning as well, the node will kept changing so ComfyUI cannot properly cached this node even after fixed seed, therefore the entire workflow will run again if we decide to rerun using the very same seed, very inefficient, I dont know what happened here, 

WARNING: FluxPromptGenerator.IS_CHANGED() got an unexpected keyword argument 'seed'
Prompt executed in 0.00 seconds
got prompt
WARNING: FluxPromptGenerator.IS_CHANGED() got an unexpected keyword argument 'seed'
Prompt executed in 0.00 seconds
